// <auto-generated />
namespace AcunMedyaTravelProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig_first1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_first1));
        
        string IMigrationMetadata.Id
        {
            get { return "202504110111182_mig_first1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
